/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables.records;


import conduit.jooq.models.tables.Articles;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticlesRecord extends UpdatableRecordImpl<ArticlesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.articles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.articles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.articles.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.articles.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.articles.slug</code>.
     */
    public void setSlug(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.articles.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.articles.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.articles.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.articles.content</code>.
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.articles.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.articles.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.articles.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.articles.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.articles.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.articles.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.articles.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticlesRecord
     */
    public ArticlesRecord() {
        super(Articles.ARTICLES);
    }

    /**
     * Create a detached, initialised ArticlesRecord
     */
    public ArticlesRecord(Long id, String title, String slug, String description, String content, Long authorId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Articles.ARTICLES);

        setId(id);
        setTitle(title);
        setSlug(slug);
        setDescription(description);
        setContent(content);
        setAuthorId(authorId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
