/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables.records;


import conduit.jooq.models.tables.ArticleFavorite;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticleFavoriteRecord extends UpdatableRecordImpl<ArticleFavoriteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article_favorite.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_favorite.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article_favorite.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_favorite.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.article_favorite.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article_favorite.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord() {
        super(ArticleFavorite.ARTICLE_FAVORITE);
    }

    /**
     * Create a detached, initialised ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord(Long articleId, Long userId, LocalDateTime createdAt) {
        super(ArticleFavorite.ARTICLE_FAVORITE);

        setArticleId(articleId);
        setUserId(userId);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
