/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables.records;


import conduit.jooq.models.tables.ArticleTag;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticleTagRecord extends UpdatableRecordImpl<ArticleTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article_tag.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_tag.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article_tag.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_tag.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.article_tag.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article_tag.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleTagRecord
     */
    public ArticleTagRecord() {
        super(ArticleTag.ARTICLE_TAG);
    }

    /**
     * Create a detached, initialised ArticleTagRecord
     */
    public ArticleTagRecord(Long articleId, Long tagId, LocalDateTime createdAt) {
        super(ArticleTag.ARTICLE_TAG);

        setArticleId(articleId);
        setTagId(tagId);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
