/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables.records;


import conduit.jooq.models.tables.UserFollower;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserFollowerRecord extends UpdatableRecordImpl<UserFollowerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_follower.from_id</code>.
     */
    public void setFromId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_follower.from_id</code>.
     */
    public Long getFromId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_follower.to_id</code>.
     */
    public void setToId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_follower.to_id</code>.
     */
    public Long getToId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserFollowerRecord
     */
    public UserFollowerRecord() {
        super(UserFollower.USER_FOLLOWER);
    }

    /**
     * Create a detached, initialised UserFollowerRecord
     */
    public UserFollowerRecord(Long fromId, Long toId) {
        super(UserFollower.USER_FOLLOWER);

        setFromId(fromId);
        setToId(toId);
        resetTouchedOnNotNull();
    }
}
