/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables;


import conduit.jooq.models.Keys;
import conduit.jooq.models.Public;
import conduit.jooq.models.tables.Articles.ArticlesPath;
import conduit.jooq.models.tables.Users.UsersPath;
import conduit.jooq.models.tables.records.ArticleFavoriteRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticleFavorite extends TableImpl<ArticleFavoriteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.article_favorite</code>
     */
    public static final ArticleFavorite ARTICLE_FAVORITE = new ArticleFavorite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleFavoriteRecord> getRecordType() {
        return ArticleFavoriteRecord.class;
    }

    /**
     * The column <code>public.article_favorite.article_id</code>.
     */
    public final TableField<ArticleFavoriteRecord, Long> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.article_favorite.user_id</code>.
     */
    public final TableField<ArticleFavoriteRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.article_favorite.created_at</code>.
     */
    public final TableField<ArticleFavoriteRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.article_favorite</code> table reference
     */
    public ArticleFavorite(String alias) {
        this(DSL.name(alias), ARTICLE_FAVORITE);
    }

    /**
     * Create an aliased <code>public.article_favorite</code> table reference
     */
    public ArticleFavorite(Name alias) {
        this(alias, ARTICLE_FAVORITE);
    }

    /**
     * Create a <code>public.article_favorite</code> table reference
     */
    public ArticleFavorite() {
        this(DSL.name("article_favorite"), null);
    }

    public <O extends Record> ArticleFavorite(Table<O> path, ForeignKey<O, ArticleFavoriteRecord> childPath, InverseForeignKey<O, ArticleFavoriteRecord> parentPath) {
        super(path, childPath, parentPath, ARTICLE_FAVORITE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArticleFavoritePath extends ArticleFavorite implements Path<ArticleFavoriteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArticleFavoritePath(Table<O> path, ForeignKey<O, ArticleFavoriteRecord> childPath, InverseForeignKey<O, ArticleFavoriteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArticleFavoritePath(Name alias, Table<ArticleFavoriteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArticleFavoritePath as(String alias) {
            return new ArticleFavoritePath(DSL.name(alias), this);
        }

        @Override
        public ArticleFavoritePath as(Name alias) {
            return new ArticleFavoritePath(alias, this);
        }

        @Override
        public ArticleFavoritePath as(Table<?> alias) {
            return new ArticleFavoritePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ArticleFavoriteRecord> getPrimaryKey() {
        return Keys.ARTICLE_FAVORITE_PKEY;
    }

    @Override
    public List<ForeignKey<ArticleFavoriteRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTICLE_FAVORITE__FK_ARTICLE_FAVORITE_ARTICLE_ID, Keys.ARTICLE_FAVORITE__FK_ARTICLE_FAVORITE_USER_ID);
    }

    private transient ArticlesPath _articles;

    /**
     * Get the implicit join path to the <code>public.articles</code> table.
     */
    public ArticlesPath articles() {
        if (_articles == null)
            _articles = new ArticlesPath(this, Keys.ARTICLE_FAVORITE__FK_ARTICLE_FAVORITE_ARTICLE_ID, null);

        return _articles;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ARTICLE_FAVORITE__FK_ARTICLE_FAVORITE_USER_ID, null);

        return _users;
    }

    @Override
    public ArticleFavorite as(String alias) {
        return new ArticleFavorite(DSL.name(alias), this);
    }

    @Override
    public ArticleFavorite as(Name alias) {
        return new ArticleFavorite(alias, this);
    }

    @Override
    public ArticleFavorite as(Table<?> alias) {
        return new ArticleFavorite(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleFavorite rename(String name) {
        return new ArticleFavorite(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleFavorite rename(Name name) {
        return new ArticleFavorite(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleFavorite rename(Table<?> name) {
        return new ArticleFavorite(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite where(Condition condition) {
        return new ArticleFavorite(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleFavorite where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleFavorite where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleFavorite where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleFavorite where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleFavorite whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
