/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables;


import conduit.jooq.models.Keys;
import conduit.jooq.models.Public;
import conduit.jooq.models.tables.Articles.ArticlesPath;
import conduit.jooq.models.tables.Tags.TagsPath;
import conduit.jooq.models.tables.records.ArticleTagRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticleTag extends TableImpl<ArticleTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.article_tag</code>
     */
    public static final ArticleTag ARTICLE_TAG = new ArticleTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleTagRecord> getRecordType() {
        return ArticleTagRecord.class;
    }

    /**
     * The column <code>public.article_tag.article_id</code>.
     */
    public final TableField<ArticleTagRecord, Long> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.article_tag.tag_id</code>.
     */
    public final TableField<ArticleTagRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.article_tag.created_at</code>.
     */
    public final TableField<ArticleTagRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private ArticleTag(Name alias, Table<ArticleTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ArticleTag(Name alias, Table<ArticleTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.article_tag</code> table reference
     */
    public ArticleTag(String alias) {
        this(DSL.name(alias), ARTICLE_TAG);
    }

    /**
     * Create an aliased <code>public.article_tag</code> table reference
     */
    public ArticleTag(Name alias) {
        this(alias, ARTICLE_TAG);
    }

    /**
     * Create a <code>public.article_tag</code> table reference
     */
    public ArticleTag() {
        this(DSL.name("article_tag"), null);
    }

    public <O extends Record> ArticleTag(Table<O> path, ForeignKey<O, ArticleTagRecord> childPath, InverseForeignKey<O, ArticleTagRecord> parentPath) {
        super(path, childPath, parentPath, ARTICLE_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArticleTagPath extends ArticleTag implements Path<ArticleTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArticleTagPath(Table<O> path, ForeignKey<O, ArticleTagRecord> childPath, InverseForeignKey<O, ArticleTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArticleTagPath(Name alias, Table<ArticleTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArticleTagPath as(String alias) {
            return new ArticleTagPath(DSL.name(alias), this);
        }

        @Override
        public ArticleTagPath as(Name alias) {
            return new ArticleTagPath(alias, this);
        }

        @Override
        public ArticleTagPath as(Table<?> alias) {
            return new ArticleTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ArticleTagRecord> getPrimaryKey() {
        return Keys.ARTICLE_TAG_PKEY;
    }

    @Override
    public List<ForeignKey<ArticleTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTICLE_TAG__FK_ARTICLE_TAG_ARTICLE_ID, Keys.ARTICLE_TAG__FK_ARTICLE_TAG_TAG_ID);
    }

    private transient ArticlesPath _articles;

    /**
     * Get the implicit join path to the <code>public.articles</code> table.
     */
    public ArticlesPath articles() {
        if (_articles == null)
            _articles = new ArticlesPath(this, Keys.ARTICLE_TAG__FK_ARTICLE_TAG_ARTICLE_ID, null);

        return _articles;
    }

    private transient TagsPath _tags;

    /**
     * Get the implicit join path to the <code>public.tags</code> table.
     */
    public TagsPath tags() {
        if (_tags == null)
            _tags = new TagsPath(this, Keys.ARTICLE_TAG__FK_ARTICLE_TAG_TAG_ID, null);

        return _tags;
    }

    @Override
    public ArticleTag as(String alias) {
        return new ArticleTag(DSL.name(alias), this);
    }

    @Override
    public ArticleTag as(Name alias) {
        return new ArticleTag(alias, this);
    }

    @Override
    public ArticleTag as(Table<?> alias) {
        return new ArticleTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTag rename(String name) {
        return new ArticleTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTag rename(Name name) {
        return new ArticleTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleTag rename(Table<?> name) {
        return new ArticleTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag where(Condition condition) {
        return new ArticleTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArticleTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArticleTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
