/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables;


import conduit.jooq.models.Keys;
import conduit.jooq.models.Public;
import conduit.jooq.models.tables.ArticleFavorite.ArticleFavoritePath;
import conduit.jooq.models.tables.ArticleTag.ArticleTagPath;
import conduit.jooq.models.tables.Comments.CommentsPath;
import conduit.jooq.models.tables.Tags.TagsPath;
import conduit.jooq.models.tables.Users.UsersPath;
import conduit.jooq.models.tables.records.ArticlesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Articles extends TableImpl<ArticlesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.articles</code>
     */
    public static final Articles ARTICLES = new Articles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticlesRecord> getRecordType() {
        return ArticlesRecord.class;
    }

    /**
     * The column <code>public.articles.id</code>.
     */
    public final TableField<ArticlesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.articles.title</code>.
     */
    public final TableField<ArticlesRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.articles.slug</code>.
     */
    public final TableField<ArticlesRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.VARCHAR(250).nullable(false), this, "");

    /**
     * The column <code>public.articles.description</code>.
     */
    public final TableField<ArticlesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.articles.content</code>.
     */
    public final TableField<ArticlesRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.articles.author_id</code>.
     */
    public final TableField<ArticlesRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.articles.created_at</code>.
     */
    public final TableField<ArticlesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.articles.updated_at</code>.
     */
    public final TableField<ArticlesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Articles(Name alias, Table<ArticlesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Articles(Name alias, Table<ArticlesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.articles</code> table reference
     */
    public Articles(String alias) {
        this(DSL.name(alias), ARTICLES);
    }

    /**
     * Create an aliased <code>public.articles</code> table reference
     */
    public Articles(Name alias) {
        this(alias, ARTICLES);
    }

    /**
     * Create a <code>public.articles</code> table reference
     */
    public Articles() {
        this(DSL.name("articles"), null);
    }

    public <O extends Record> Articles(Table<O> path, ForeignKey<O, ArticlesRecord> childPath, InverseForeignKey<O, ArticlesRecord> parentPath) {
        super(path, childPath, parentPath, ARTICLES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArticlesPath extends Articles implements Path<ArticlesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArticlesPath(Table<O> path, ForeignKey<O, ArticlesRecord> childPath, InverseForeignKey<O, ArticlesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArticlesPath(Name alias, Table<ArticlesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArticlesPath as(String alias) {
            return new ArticlesPath(DSL.name(alias), this);
        }

        @Override
        public ArticlesPath as(Name alias) {
            return new ArticlesPath(alias, this);
        }

        @Override
        public ArticlesPath as(Table<?> alias) {
            return new ArticlesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ArticlesRecord, Long> getIdentity() {
        return (Identity<ArticlesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ArticlesRecord> getPrimaryKey() {
        return Keys.ARTICLES_PKEY;
    }

    @Override
    public List<UniqueKey<ArticlesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_ARTICLES_SLUG, Keys.UK_ARTICLES_TITLE);
    }

    @Override
    public List<ForeignKey<ArticlesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ARTICLES__FK_ARTICLES_AUTHOR);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ARTICLES__FK_ARTICLES_AUTHOR, null);

        return _users;
    }

    private transient ArticleFavoritePath _articleFavorite;

    /**
     * Get the implicit to-many join path to the
     * <code>public.article_favorite</code> table
     */
    public ArticleFavoritePath articleFavorite() {
        if (_articleFavorite == null)
            _articleFavorite = new ArticleFavoritePath(this, null, Keys.ARTICLE_FAVORITE__FK_ARTICLE_FAVORITE_ARTICLE_ID.getInverseKey());

        return _articleFavorite;
    }

    private transient ArticleTagPath _articleTag;

    /**
     * Get the implicit to-many join path to the <code>public.article_tag</code>
     * table
     */
    public ArticleTagPath articleTag() {
        if (_articleTag == null)
            _articleTag = new ArticleTagPath(this, null, Keys.ARTICLE_TAG__FK_ARTICLE_TAG_ARTICLE_ID.getInverseKey());

        return _articleTag;
    }

    private transient CommentsPath _comments;

    /**
     * Get the implicit to-many join path to the <code>public.comments</code>
     * table
     */
    public CommentsPath comments() {
        if (_comments == null)
            _comments = new CommentsPath(this, null, Keys.COMMENTS__FK_COMMENTS_ARTICLE_ID.getInverseKey());

        return _comments;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.tags</code>
     * table
     */
    public TagsPath tags() {
        return articleTag().tags();
    }

    @Override
    public Articles as(String alias) {
        return new Articles(DSL.name(alias), this);
    }

    @Override
    public Articles as(Name alias) {
        return new Articles(alias, this);
    }

    @Override
    public Articles as(Table<?> alias) {
        return new Articles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Articles rename(String name) {
        return new Articles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Articles rename(Name name) {
        return new Articles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Articles rename(Table<?> name) {
        return new Articles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles where(Condition condition) {
        return new Articles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Articles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Articles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Articles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Articles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Articles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
