/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models.tables;


import conduit.jooq.models.Keys;
import conduit.jooq.models.Public;
import conduit.jooq.models.tables.Users.UsersPath;
import conduit.jooq.models.tables.records.UserFollowerRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserFollower extends TableImpl<UserFollowerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_follower</code>
     */
    public static final UserFollower USER_FOLLOWER = new UserFollower();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserFollowerRecord> getRecordType() {
        return UserFollowerRecord.class;
    }

    /**
     * The column <code>public.user_follower.from_id</code>.
     */
    public final TableField<UserFollowerRecord, Long> FROM_ID = createField(DSL.name("from_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_follower.to_id</code>.
     */
    public final TableField<UserFollowerRecord, Long> TO_ID = createField(DSL.name("to_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private UserFollower(Name alias, Table<UserFollowerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserFollower(Name alias, Table<UserFollowerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_follower</code> table reference
     */
    public UserFollower(String alias) {
        this(DSL.name(alias), USER_FOLLOWER);
    }

    /**
     * Create an aliased <code>public.user_follower</code> table reference
     */
    public UserFollower(Name alias) {
        this(alias, USER_FOLLOWER);
    }

    /**
     * Create a <code>public.user_follower</code> table reference
     */
    public UserFollower() {
        this(DSL.name("user_follower"), null);
    }

    public <O extends Record> UserFollower(Table<O> path, ForeignKey<O, UserFollowerRecord> childPath, InverseForeignKey<O, UserFollowerRecord> parentPath) {
        super(path, childPath, parentPath, USER_FOLLOWER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserFollowerPath extends UserFollower implements Path<UserFollowerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserFollowerPath(Table<O> path, ForeignKey<O, UserFollowerRecord> childPath, InverseForeignKey<O, UserFollowerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserFollowerPath(Name alias, Table<UserFollowerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserFollowerPath as(String alias) {
            return new UserFollowerPath(DSL.name(alias), this);
        }

        @Override
        public UserFollowerPath as(Name alias) {
            return new UserFollowerPath(alias, this);
        }

        @Override
        public UserFollowerPath as(Table<?> alias) {
            return new UserFollowerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserFollowerRecord> getPrimaryKey() {
        return Keys.USER_FOLLOWER_PKEY;
    }

    @Override
    public List<ForeignKey<UserFollowerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_FOLLOWER__USER_FOLLOWER_FROM_ID_FKEY, Keys.USER_FOLLOWER__USER_FOLLOWER_TO_ID_FKEY);
    }

    private transient UsersPath _userFollowerFromIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>user_follower_from_id_fkey</code> key.
     */
    public UsersPath userFollowerFromIdFkey() {
        if (_userFollowerFromIdFkey == null)
            _userFollowerFromIdFkey = new UsersPath(this, Keys.USER_FOLLOWER__USER_FOLLOWER_FROM_ID_FKEY, null);

        return _userFollowerFromIdFkey;
    }

    private transient UsersPath _userFollowerToIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>user_follower_to_id_fkey</code> key.
     */
    public UsersPath userFollowerToIdFkey() {
        if (_userFollowerToIdFkey == null)
            _userFollowerToIdFkey = new UsersPath(this, Keys.USER_FOLLOWER__USER_FOLLOWER_TO_ID_FKEY, null);

        return _userFollowerToIdFkey;
    }

    @Override
    public UserFollower as(String alias) {
        return new UserFollower(DSL.name(alias), this);
    }

    @Override
    public UserFollower as(Name alias) {
        return new UserFollower(alias, this);
    }

    @Override
    public UserFollower as(Table<?> alias) {
        return new UserFollower(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFollower rename(String name) {
        return new UserFollower(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFollower rename(Name name) {
        return new UserFollower(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserFollower rename(Table<?> name) {
        return new UserFollower(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower where(Condition condition) {
        return new UserFollower(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserFollower where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserFollower where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserFollower where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserFollower where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserFollower whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
