/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models;


import conduit.jooq.models.tables.ArticleFavorite;
import conduit.jooq.models.tables.ArticleTag;
import conduit.jooq.models.tables.Articles;
import conduit.jooq.models.tables.Comments;
import conduit.jooq.models.tables.Tags;
import conduit.jooq.models.tables.UserFollower;
import conduit.jooq.models.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.article_favorite</code>.
     */
    public final ArticleFavorite ARTICLE_FAVORITE = ArticleFavorite.ARTICLE_FAVORITE;

    /**
     * The table <code>public.article_tag</code>.
     */
    public final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * The table <code>public.articles</code>.
     */
    public final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>public.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.tags</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_follower</code>.
     */
    public final UserFollower USER_FOLLOWER = UserFollower.USER_FOLLOWER;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ARTICLE_ID_SEQ,
            Sequences.COMMENT_ID_SEQ,
            Sequences.TAG_ID_SEQ,
            Sequences.USER_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ArticleFavorite.ARTICLE_FAVORITE,
            ArticleTag.ARTICLE_TAG,
            Articles.ARTICLES,
            Comments.COMMENTS,
            Tags.TAGS,
            UserFollower.USER_FOLLOWER,
            Users.USERS
        );
    }
}
