/*
 * This file is generated by jOOQ.
 */
package conduit.jooq.models;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.article_id_seq</code>
     */
    public static final Sequence<Long> ARTICLE_ID_SEQ = Internal.createSequence("article_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 10, null, null, false, null);

    /**
     * The sequence <code>public.comment_id_seq</code>
     */
    public static final Sequence<Long> COMMENT_ID_SEQ = Internal.createSequence("comment_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 10, null, null, false, null);

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = Internal.createSequence("tag_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 10, null, null, false, null);

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = Internal.createSequence("user_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), 100, 10, null, null, false, null);
}
