package conduit.config;

import conduit.ApplicationProperties;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
class OpenAPIConfig {

    @Bean
    OpenAPI openApi(ApplicationProperties properties) {
        var openapi = properties.openapi();
        Contact contact = new Contact()
                .name(openapi.contact().name())
                .email(openapi.contact().email());
        Info info = new Info()
                .title(openapi.title())
                .description(openapi.description())
                .version(openapi.version())
                .contact(contact);
        return new OpenAPI()
                .info(info)
                .addSecurityItem(new SecurityRequirement().addList("Authorization"))
                .components(new Components().addSecuritySchemes("Token", createAPIKeyScheme()));
    }

    private SecurityScheme createAPIKeyScheme() {
        return new SecurityScheme()
                .in(SecurityScheme.In.HEADER)
                .type(SecurityScheme.Type.APIKEY)
                .name("Authorization")
                .description(
                        """
                        For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in.
                        This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.

                        A JWT token is generated by the API by either registering via /users or logging in via /users/login.

                        The following format must be in the 'Authorization' header :

                        <pre><code>Token xxxxxx.yyyyyyy.zzzzzz</code></pre>
                        """);
    }
}
